fix: ci test 8

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,22 +14,22 @@ on:
 name: General
 
 jobs:
-  build-ubuntu-latest:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
+  # build-ubuntu-latest:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
 
-    name: build - ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install stable toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: nightly
-          override: true
-      - name: build - ubuntu-latest
-        if: success() || failure()
-        run: chmod 777 ./ci_scripts/build-ubuntu.sh && ./ci_scripts/build-ubuntu.sh
+  #   name: build - ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Install stable toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         profile: minimal
+  #         toolchain: nightly
+  #         override: true
+  #     - name: build - ubuntu-latest
+  #       if: success() || failure()
+  #       run: chmod 777 ./ci_scripts/build-ubuntu.sh && ./ci_scripts/build-ubuntu.sh
 
 
   build-macos-latest:
@@ -49,46 +49,46 @@ jobs:
         if: success() || failure()
         run: chmod 777 ./ci_scripts/build-macos.sh && ./ci_scripts/build-macos.sh
 
-  lint:
-    strategy:
-      matrix:
-        platform: [ ubuntu-latest ]
-    runs-on: ${{ matrix.platform }}
-    timeout-minutes: 60
+  # lint:
+  #   strategy:
+  #     matrix:
+  #       platform: [ ubuntu-latest ]
+  #   runs-on: ${{ matrix.platform }}
+  #   timeout-minutes: 60
 
-    name: lint - ${{ matrix.crate }} - ${{ matrix.platform }}
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@v3
-      - name: Install stable toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: nightly
-          override: true
-          components: rustfmt, clippy
-      - name: lint - ubuntu-latest
-        if: success() || failure()
-        run: chmod 777 ./ci_scripts/lint-ubuntu.sh && ./ci_scripts/lint-ubuntu.sh
+  #   name: lint - ${{ matrix.crate }} - ${{ matrix.platform }}
+  #   steps:
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
+  #     - name: Install stable toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         profile: minimal
+  #         toolchain: nightly
+  #         override: true
+  #         components: rustfmt, clippy
+  #     - name: lint - ubuntu-latest
+  #       if: success() || failure()
+  #       run: chmod 777 ./ci_scripts/lint-ubuntu.sh && ./ci_scripts/lint-ubuntu.sh
 
 
-  test:
-    strategy:
-      matrix:
-        platform: [ ubuntu-latest ]
-    runs-on: ${{ matrix.platform }}
-    timeout-minutes: 60
+  # test:
+  #   strategy:
+  #     matrix:
+  #       platform: [ ubuntu-latest ]
+  #   runs-on: ${{ matrix.platform }}
+  #   timeout-minutes: 60
 
-    name: test - ${{ matrix.crate }} - ${{ matrix.platform }}
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@v3
-      - name: Install stable toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: nightly
-          override: true
-      - name: test ubuntu-latest
-        if: success() || failure()
-        run: chmod 777 ./ci_scripts/test-ubuntu.sh && ./ci_scripts/test-ubuntu.sh
+  #   name: test - ${{ matrix.crate }} - ${{ matrix.platform }}
+  #   steps:
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
+  #     - name: Install stable toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         profile: minimal
+  #         toolchain: nightly
+  #         override: true
+  #     - name: test ubuntu-latest
+  #       if: success() || failure()
+  #       run: chmod 777 ./ci_scripts/test-ubuntu.sh && ./ci_scripts/test-ubuntu.sh
